[profile.default]
src = "contracts"
solc_version = "0.8.26"
optimizer = true # enable or disable the solc optimizer
optimizer_runs = 10000 # the number of optimizer runs
verbosity = 3 # The verbosity of tests
isolate = true # enable or disable the isolate mode for calculating gas usage correctly
libs = ["lib"]
